#!/bin/sh
iptables -I INPUT -p udp --destination-port 5555 -j ACCEPT
iptables -I INPUT -p udp --destination-port 992 -j ACCEPT
iptables -I INPUT -p udp --destination-port 1194 -j ACCEPT
iptables -I INPUT -p tcp --destination-port 5555 -j ACCEPT
iptables -I INPUT -p tcp --destination-port 992 -j ACCEPT
iptables -I INPUT -p tcp --destination-port 1194 -j ACCEPT
